### ISSUE TITLE
Save to file is awkward

### ISSUE THREAD

**Issue by markusdregi** [equinor/configsuite-tui#47]
When saving to a new file I'm struggling to get to the text field to type a filename without first: selecting an existing file, erase the existing filename and write the filename I intended. Am I missing something?

**Comment by haavardnk** [comment]
I guess this is how npyscreen works. But try TAB to switch to the text field.

**Comment by markusdregi** [comment]
```yaml
!# configsuite-tui: schema=List
name: Markus
owned_cars:
- type: The best
  brand: Rocketroll
  previous_owners:
  - Atle Johny
```

I then edited as following:

```yaml
!# configsuite-tui: schema=List
name: Markus
owned_cars:
- type: The best
  brand: Rocketroll
  previous_owners:
    Atle: Johny
```

After which I open the file again using `configsuite_tui config.yml` and select `owned_cars`, `named_dict`, `previous_owners`, `string [0]` and I get

```
Traceback (most recent call last):
  File "/Users/mfane/Development/plugin_test/env/bin/configsuite_tui", line 8, in <module>
    sys.exit(main())
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/configsuite_tui/__main__.py", line 17, in main
    tui(config, schema)
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/configsuite_tui/tui.py", line 68, in tui
    App.run()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/wgtitlefield.py", line 119, in edit
    self.entry_widget.edit()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/wgtextbox.py", line 383, in edit
    self.get_and_use_key_press()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/wgwidget.py", line 617, in get_and_use_key_press
    self.try_adjust_widgets()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/npyscreen/wgwidget.py", line 547, in try_adjust_widgets
    self.parent.adjust_widgets()
  File "/Users/mfane/Development/plugin_test/env/lib/python3.7/site-packages/configsuite_tui/tui.py", line 293, in adjust_widgets
    value = self.schemawidgets[w].value
KeyError: 1
```

**Comment by markusdregi** [comment]
`TAB` worked excellently! This is not an issue...
